In [1]:
import nltk
nltk.download('punkt_tab')
nltk.download('wordnet')

[nltk_data] Downloading package punkt_tab to
[nltk_data]     C:\Users\SALEM\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt_tab is already up-to-date!
[nltk_data] Downloading package wordnet to
[nltk_data]     C:\Users\SALEM\AppData\Roaming\nltk_data...
[nltk_data]   Package wordnet is already up-to-date!

True

In [2]:
import nltk
nltk.download('punkt')
nltk.download('stopwords')
nltk.download('wordnet')

[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\SALEM\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\SALEM\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package wordnet to
[nltk_data]     C:\Users\SALEM\AppData\Roaming\nltk_data...
[nltk_data]   Package wordnet is already up-to-date!

True

In [3]:
#importing pandas to read files and put them in data frame
import pandas
#reading the file
df=pandas.read_csv("satm_dataset_1000_rows.csv")
#printing the file
df

,Task Text,Category,Difficulty,Deadline (days),Time Taken (hours),Importance
0,those calculus problems from class no rush,Homework,Medium,7,1.7,Low
1,prep for databases quiz,Quiz,Easy,2,1.3,High
2,do CHEM hw,Homework,Medium,5,2.4,Medium
3,lit midterm prep this week,Exam,Hard,5,6.1,Medium
4,oh no bioo exam tmr study literally tonight,Exam,Medium,1,3.9,High
...,...,...,...,...,...,...
995,db assignment ch7 scheduled,Homework,Easy,5,1.8,Medium
996,mini test BIO - low priority,Quiz,Hard,7,1.5,Low
997,bio hw ch6 - this week,Homework,Hard,3,5.0,Medium
998,networks final exam study idk when,Exam,Hard,6,5.0,Low
999,network project draft v1 due tmr!!,Project,Hard,1,6.7,High

In [4]:
# to check if we have null values
df.isnull().sum()

Task Text             0
Category              0
Difficulty            0
Deadline (days)       0
Time Taken (hours)    0
Importance            0
dtype: int64

In [5]:
# Display data types and basic info
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 6 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Task Text           1000 non-null   str
 1   Category            1000 non-null   str
 2   Difficulty          1000 non-null   str
 3   Deadline (days)     1000 non-null   int64
 4   Time Taken (hours)  1000 non-null   float64
 5   Importance          1000 non-null   str
dtypes: float64(1), int64(1), str(4)
memory usage: 47.0 KB

In [6]:
# Check for duplicate rows
duplicate_rows = df.duplicated().sum()
if duplicate_rows > 0:
    print(f"Found {duplicate_rows} duplicate rows. Dropping them...")
    df.drop_duplicates(inplace=True)
    print("Duplicate rows dropped.")
else:
    print("No duplicate rows found.")

display(df.head())

No duplicate rows found.

,Task Text,Category,Difficulty,Deadline (days),Time Taken (hours),Importance
0,those calculus problems from class no rush,Homework,Medium,7,1.7,Low
1,prep for databases quiz,Quiz,Easy,2,1.3,High
2,do CHEM hw,Homework,Medium,5,2.4,Medium
3,lit midterm prep this week,Exam,Hard,5,6.1,Medium
4,oh no bioo exam tmr study literally tonight,Exam,Medium,1,3.9,High

In [7]:
# Category Column
# Check unique values in 'Category' before standardization
print("Unique values in 'Category' column before standardization:")
display(df['Category'].unique())

# Standardize 'Category' column to title case
df['Category'] = df['Category'].str.title()

# Check unique values in 'Category' after standardization
print("\nUnique values in 'Category' column after standardization:")
display(df['Category'].unique())

# Difficulty Column
# Check unique values in 'Difficulty' before standardization
print("\nUnique values in 'Difficulty' column before standardization:")
display(df['Difficulty'].unique())

# Standardize 'Difficulty' column to title case
df['Difficulty'] = df['Difficulty'].str.title()

# Check unique values in 'Difficulty' after standardization
print("\nUnique values in 'Difficulty' column after standardization:")
display(df['Difficulty'].unique())

# Importance Column
# Check unique values in 'Importance' before standardization
print("\nUnique values in 'Importance' column before standardization:")
display(df['Importance'].unique())

# Standardize 'Importance' column to title case
df['Importance'] = df['Importance'].str.title()

# Check unique values in 'Importance' after standardization
print("\nUnique values in 'Importance' column after standardization:")
display(df['Importance'].unique())

Unique values in 'Category' column before standardization:

<StringArray>
['Homework', 'Quiz', 'Exam', 'Project']
Length: 4, dtype: str

Unique values in 'Category' column after standardization:

<StringArray>
['Homework', 'Quiz', 'Exam', 'Project']
Length: 4, dtype: str

Unique values in 'Difficulty' column before standardization:

<StringArray>
['Medium', 'Easy', 'Hard']
Length: 3, dtype: str

Unique values in 'Difficulty' column after standardization:

<StringArray>
['Medium', 'Easy', 'Hard']
Length: 3, dtype: str

Unique values in 'Importance' column before standardization:

<StringArray>
['Low', 'High', 'Medium']
Length: 3, dtype: str

Unique values in 'Importance' column after standardization:

<StringArray>
['Low', 'High', 'Medium']
Length: 3, dtype: str

In [8]:
df

,Task Text,Category,Difficulty,Deadline (days),Time Taken (hours),Importance
0,those calculus problems from class no rush,Homework,Medium,7,1.7,Low
1,prep for databases quiz,Quiz,Easy,2,1.3,High
2,do CHEM hw,Homework,Medium,5,2.4,Medium
3,lit midterm prep this week,Exam,Hard,5,6.1,Medium
4,oh no bioo exam tmr study literally tonight,Exam,Medium,1,3.9,High
...,...,...,...,...,...,...
995,db assignment ch7 scheduled,Homework,Easy,5,1.8,Medium
996,mini test BIO - low priority,Quiz,Hard,7,1.5,Low
997,bio hw ch6 - this week,Homework,Hard,3,5.0,Medium
998,networks final exam study idk when,Exam,Hard,6,5.0,Low
999,network project draft v1 due tmr!!,Project,Hard,1,6.7,High

### Step 1: DATA CLEANING (TEXT PROCESSING)

In [9]:
import re
import string

def clean_text(text):
    # Convert to lowercase
    text = str(text).lower()

    # Remove special characters, punctuation, and emojis
    text = re.sub(f'[{re.escape(string.punctuation)}]', '', text)
    text = re.sub(r'\s+', ' ', text).strip() # Remove extra whitespaces
    text = re.sub(r'[\U0001F600-\U0001F64F\U0001F300-\U0001F5FF\U0001F680-\U0001F6FF\U0001F1E0-\U0001F1FF]', '', text)

    # Normalize common abbreviations
    text = text.replace('hw', 'homework')
    text = text.replace('ppt', 'presentation')
    text = text.replace('bio', 'biology')

    # Handle unclear or low-quality entries (simple replacement for 'idk', could be expanded)
    text = text.replace('idk', 'unknown')

    return text

df['Cleaned_Task_Text'] = df['Task Text'].apply(clean_text)

print("Original Task Text vs. Cleaned Task Text (first 5 rows):")
display(df[['Task Text', 'Cleaned_Task_Text']].head())

Original Task Text vs. Cleaned Task Text (first 5 rows):

,Task Text,Cleaned_Task_Text
0,those calculus problems from class no rush,those calculus problems from class no rush
1,prep for databases quiz,prep for databases quiz
2,do CHEM hw,do chem homework
3,lit midterm prep this week,lit midterm prep this week
4,oh no bioo exam tmr study literally tonight,oh no biologyo exam tmr study literally tonight

### Step 2: NLP PREPROCESSING

In [10]:
from nltk.tokenize import word_tokenize
from nltk.corpus import stopwords
from nltk.stem import WordNetLemmatizer

# Initialize stop words and lemmatizer
stop_words = set(stopwords.words('english'))
lemmatizer = WordNetLemmatizer()

def nlp_preprocess(text):
    # Tokenization
    tokens = word_tokenize(text)

    # Remove stop words and apply lemmatization
    processed_tokens = []
    for token in tokens:
        if token not in stop_words:
            processed_tokens.append(lemmatizer.lemmatize(token))

    return ' '.join(processed_tokens)

df['Processed_Task_Text'] = df['Cleaned_Task_Text'].apply(nlp_preprocess)

print("Original, Cleaned, and Processed Task Text (first 5 rows):")
display(df[['Task Text', 'Cleaned_Task_Text', 'Processed_Task_Text']].head())

Original, Cleaned, and Processed Task Text (first 5 rows):

,Task Text,Cleaned_Task_Text,Processed_Task_Text
0,those calculus problems from class no rush,those calculus problems from class no rush,calculus problem class rush
1,prep for databases quiz,prep for databases quiz,prep database quiz
2,do CHEM hw,do chem homework,chem homework
3,lit midterm prep this week,lit midterm prep this week,lit midterm prep week
4,oh no bioo exam tmr study literally tonight,oh no biologyo exam tmr study literally tonight,oh biologyo exam tmr study literally tonight

### Step 3: TEXT VECTORIZATION

In [11]:
from nltk.tokenize import word_tokenize
from nltk.corpus import stopwords
from nltk.stem import WordNetLemmatizer

# Initialize stop words and lemmatizer
stop_words = set(stopwords.words('english'))
lemmatizer = WordNetLemmatizer()

def nlp_preprocess(text):
    # Tokenization
    tokens = word_tokenize(text)

    # Remove stop words and apply lemmatization
    processed_tokens = []
    for token in tokens:
        if token not in stop_words:
            processed_tokens.append(lemmatizer.lemmatize(token))

    return ' '.join(processed_tokens)

df['Processed_Task_Text'] = df['Cleaned_Task_Text'].apply(nlp_preprocess)

print("Original, Cleaned, and Processed Task Text (first 5 rows):")
display(df[['Task Text', 'Cleaned_Task_Text', 'Processed_Task_Text']].head())

Original, Cleaned, and Processed Task Text (first 5 rows):

,Task Text,Cleaned_Task_Text,Processed_Task_Text
0,those calculus problems from class no rush,those calculus problems from class no rush,calculus problem class rush
1,prep for databases quiz,prep for databases quiz,prep database quiz
2,do CHEM hw,do chem homework,chem homework
3,lit midterm prep this week,lit midterm prep this week,lit midterm prep week
4,oh no bioo exam tmr study literally tonight,oh no biologyo exam tmr study literally tonight,oh biologyo exam tmr study literally tonight

In [12]:
from sklearn.feature_extraction.text import TfidfVectorizer

# Initialize TF-IDF Vectorizer
# Limiting max_features to a reasonable number to avoid excessively high-dimensional data
tfidf_vectorizer = TfidfVectorizer(max_features=1000)

# Fit and transform the 'Processed_Task_Text' column
tfidf_features = tfidf_vectorizer.fit_transform(df['Processed_Task_Text'])

print("Shape of TF-IDF feature matrix:", tfidf_features.shape)
print("Sample of TF-IDF features (first row, first 10 features, if dense):")
# Convert to array for printing, only if it's a small sample, otherwise it will be too large.
# For demonstrating, we can show a small part.
if tfidf_features.shape[0] > 0:
    print(tfidf_features[0, :10].toarray())
else:
    print("No TF-IDF features generated.")

Shape of TF-IDF feature matrix: (1000, 152)
Sample of TF-IDF features (first row, first 10 features, if dense):
[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]

In [13]:
from sklearn.feature_extraction.text import TfidfVectorizer

# Initialize TF-IDF Vectorizer
# Limiting max_features to a reasonable number to avoid excessively high-dimensional data
tfidf_vectorizer = TfidfVectorizer(max_features=1000)

# Fit and transform the 'Processed_Task_Text' column
tfidf_features = tfidf_vectorizer.fit_transform(df['Processed_Task_Text'])

print("Shape of TF-IDF feature matrix:", tfidf_features.shape)
print("Sample of TF-IDF features (first row, first 10 features, if dense):")
# Convert to array for printing, only if it's a small sample, otherwise it will be too large.
# For demonstrating, we can show a small part.
if tfidf_features.shape[0] > 0:
    print(tfidf_features[0, :10].toarray())
else:
    print("No TF-IDF features generated.")

Shape of TF-IDF feature matrix: (1000, 152)
Sample of TF-IDF features (first row, first 10 features, if dense):
[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]

In [14]:
import nltk
nltk.download('punkt')
nltk.download('stopwords')
nltk.download('wordnet')
nltk.download('punkt_tab')

[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\SALEM\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\SALEM\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package wordnet to
[nltk_data]     C:\Users\SALEM\AppData\Roaming\nltk_data...
[nltk_data]   Package wordnet is already up-to-date!
[nltk_data] Downloading package punkt_tab to
[nltk_data]     C:\Users\SALEM\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt_tab is already up-to-date!

True

### Step 4: HANDLE CATEGORICAL DATA

In [15]:
from sklearn.preprocessing import OneHotEncoder, LabelEncoder
import pandas as pd

# Initialize separate encoders for Category and Importance
one_hot_encoder_category = OneHotEncoder(handle_unknown='ignore', sparse_output=False)
one_hot_encoder_importance = OneHotEncoder(handle_unknown='ignore', sparse_output=False)
label_encoder = LabelEncoder()

# One-hot encode 'Category' and 'Importance'
category_encoded = one_hot_encoder_category.fit_transform(df[['Category']])
importance_encoded = one_hot_encoder_importance.fit_transform(df[['Importance']])

# Create DataFrames from one-hot encoded features
category_df = pd.DataFrame(category_encoded, columns=one_hot_encoder_category.get_feature_names_out(['Category']))
importance_df = pd.DataFrame(importance_encoded, columns=one_hot_encoder_importance.get_feature_names_out(['Importance']))

# Ordinal encode 'Difficulty'
# Define the order for Difficulty
difficulty_order = ['Easy', 'Medium', 'Hard']
# Ensure the 'Difficulty' column is of 'category' dtype with the specified order
df['Difficulty'] = pd.Categorical(df['Difficulty'], categories=difficulty_order, ordered=True)
# Map categories to numerical values (0, 1, 2...)
df['Difficulty_Encoded'] = df['Difficulty'].cat.codes

print("Encoded Categorical Features (first 5 rows):")
display(pd.concat([category_df, importance_df, df[['Difficulty_Encoded']]], axis=1).head())

Encoded Categorical Features (first 5 rows):

,Category_Exam,Category_Homework,Category_Project,Category_Quiz,Importance_High,Importance_Low,Importance_Medium,Difficulty_Encoded
0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,1
1,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0
2,0.0,1.0,0.0,0.0,0.0,0.0,1.0,1
3,1.0,0.0,0.0,0.0,0.0,0.0,1.0,2
4,1.0,0.0,0.0,0.0,1.0,0.0,0.0,1

### Step 5: FEATURE ENGINEERING

In [16]:
# Task length (number of words)
df['Task_Length'] = df['Processed_Task_Text'].apply(lambda x: len(x.split()))

# Urgency flag (if words like 'urgent', 'asap', 'tomorrow' appear)
urgent_keywords = ['urgent', 'asap', 'tomorrow', 'immediate']
df['Urgency_Flag'] = df['Cleaned_Task_Text'].apply(lambda x: 1 if any(keyword in x for keyword in urgent_keywords) else 0)

# Time pressure = Deadline / Time Taken
# Handle potential division by zero or very small Time Taken values to avoid NaNs or Infs
df['Time_Pressure'] = df['Deadline (days)'] / df['Time Taken (hours)'].replace(0, 0.001) # Replace 0 with a small number
df['Time_Pressure'] = df['Time_Pressure'].replace([float('inf'), -float('inf')], 1000) # Cap infinite values

print("Engineered Features (first 5 rows):")
display(df[['Task_Length', 'Urgency_Flag', 'Time_Pressure']].head())

Engineered Features (first 5 rows):

   Task_Length  Urgency_Flag  Time_Pressure
0            4             0       4.117647
1            3             0       1.538462
2            2             0       2.083333
3            4             0       0.819672
4            7             0       0.256410

### Step 6: HANDLE NUMERICAL DATA

In [17]:
from sklearn.preprocessing import StandardScaler

# Initialize StandardScaler
scaler = StandardScaler()

# Scale 'Deadline (days)' and 'Time Taken (hours)'
df[['Deadline (days)_scaled', 'Time Taken (hours)_scaled']] = scaler.fit_transform(df[['Deadline (days)', 'Time Taken (hours)']])

print("Scaled Numerical Features (first 5 rows):")
display(df[['Deadline (days)', 'Deadline (days)_scaled', 'Time Taken (hours)', 'Time Taken (hours)_scaled']].head())

Scaled Numerical Features (first 5 rows):

,Deadline (days),Deadline (days)_scaled,Time Taken (hours),Time Taken (hours)_scaled
0,7,1.483185,1.7,-0.921226
1,2,-0.939528,1.3,-1.152559
2,5,0.514100,2.4,-0.516393
3,5,0.514100,6.1,1.623437
4,1,-1.424071,3.9,0.351106

### Step 7: HANDLE DATA QUALITY ISSUES

In [18]:
import numpy as np

# Check for missing values
print("Missing values before handling:")
display(df.isnull().sum()[df.isnull().sum() > 0])

# For simplicity, if there are any missing values, we'll fill numerical NaNs with the mean
# and categorical NaNs with the mode. Here, we assume no NaNs were introduced by previous steps.
# If any appear, this is a robust way to handle them.
for col in df.columns:
    if df[col].isnull().any():
        if pd.api.types.is_numeric_dtype(df[col]):
            df[col].fillna(df[col].mean(), inplace=True)
        else:
            df[col].fillna(df[col].mode()[0], inplace=True)

print("\nMissing values after handling:")
display(df.isnull().sum()[df.isnull().sum() > 0])

# Detect outliers in 'Time Taken (hours)' using IQR method
Q1 = df['Time Taken (hours)'].quantile(0.25)
Q3 = df['Time Taken (hours)'].quantile(0.75)
IQR = Q3 - Q1

lower_bound = Q1 - 1.5 * IQR
upper_bound = Q3 + 1.5 * IQR

outliers_count = df[(df['Time Taken (hours)'] < lower_bound) | (df['Time Taken (hours)'] > upper_bound)].shape[0]
print(f"\nNumber of outliers in 'Time Taken (hours)': {outliers_count}")

# Handle outliers by clipping (Winsorization)
df['Time Taken (hours)_clipped'] = df['Time Taken (hours)'].clip(lower=lower_bound, upper=upper_bound)

print("\n'Time Taken (hours)' original vs. clipped (first 5 rows with potential outliers):")
display(df[['Time Taken (hours)', 'Time Taken (hours)_clipped']].head())

Missing values before handling:

Series([], dtype: int64)

Missing values after handling:

Series([], dtype: int64)

Number of outliers in 'Time Taken (hours)': 0

'Time Taken (hours)' original vs. clipped (first 5 rows with potential outliers):

   Time Taken (hours)  Time Taken (hours)_clipped
0                 1.7                         1.7
1                 1.3                         1.3
2                 2.4                         2.4
3                 6.1                         6.1
4                 3.9                         3.9

### Step 8: FINAL DATASET PREPARATION

In [19]:
# Convert TF-IDF features to a DataFrame
tfidf_df = pandas.DataFrame(tfidf_features.toarray(), columns=tfidf_vectorizer.get_feature_names_out())

# Combine all features into a single DataFrame
final_features_df = pandas.concat([
    category_df,
    importance_df,
    df[['Difficulty_Encoded']],
    df[['Task_Length', 'Urgency_Flag', 'Time_Pressure']],
    df[['Deadline (days)_scaled', 'Time Taken (hours)_scaled']],
    tfidf_df
], axis=1)

# Display the shape of the final dataset
print(f"Shape of the final dataset: {final_features_df.shape}")

# Display a sample of the final cleaned data
print("Sample of the final cleaned data (first 5 rows):")
display(final_features_df.head())

# Display the list of final features
print("List of final features:")
print(final_features_df.columns.tolist())

Shape of the final dataset: (1000, 165)
Sample of the final cleaned data (first 5 rows):

,Category_Exam,Category_Homework,Category_Project,Category_Quiz,Importance_High,Importance_Low,Importance_Medium,Difficulty_Encoded,Task_Length,Urgency_Flag,...,v3,v4,v5,week,weekly,whenever,work,working,write,writing
0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,1,4,0,...,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0
1,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0,3,0,...,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0
2,0.0,1.0,0.0,0.0,0.0,0.0,1.0,1,2,0,...,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0
3,1.0,0.0,0.0,0.0,0.0,0.0,1.0,2,4,0,...,0.0,0.0,0.0,0.432187,0.0,0.0,0.0,0.0,0.0,0.0
4,1.0,0.0,0.0,0.0,1.0,0.0,0.0,1,7,0,...,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0

List of final features:
['Category_Exam', 'Category_Homework', 'Category_Project', 'Category_Quiz', 'Importance_High', 'Importance_Low', 'Importance_Medium', 'Difficulty_Encoded', 'Task_Length', 'Urgency_Flag', 'Time_Pressure', 'Deadline (days)_scaled', 'Time Taken (hours)_scaled', '10', '1012', '1013', '12', '14', '24', '35', '37', '610', '812', '911', 'ai', 'algebra', 'asap', 'assignment', 'big', 'biology', 'biologylogy', 'biologyo', 'calc', 'calculus', 'ch1', 'ch10', 'ch1011', 'ch12', 'ch13', 'ch2', 'ch23', 'ch3', 'ch34', 'ch4', 'ch46', 'ch5', 'ch56', 'ch57', 'ch6', 'ch67', 'ch68', 'ch7', 'ch79', 'ch8', 'ch810', 'ch89', 'ch9', 'ch910', 'chapter', 'chem', 'chemistry', 'chemm', 'class', 'code', 'coding', 'comp', 'cramming', 'database', 'db', 'dbms', 'deep', 'draft', 'due', 'eng', 'english', 'eventually', 'everything', 'exam', 'exercise', 'final', 'finish', 'forgot', 'got', 'group', 'hard', 'help', 'homework', 'lab', 'learning', 'lit', 'literally', 'lol', 'low', 'machine', 'math', 'midterm', 'mini', 'ml', 'mode', 'need', 'net', 'network', 'networking', 'nighter', 'note', 'oh', 'omg', 'one', 'panic', 'phys', 'physic', 'pop', 'practice', 'prep', 'presentation', 'priority', 'problem', 'programming', 'project', 'quick', 'quiz', 'report', 'research', 'review', 'revise', 'revision', 'rn', 'rush', 'scheduled', 'sci', 'session', 'set', 'sheet', 'slide', 'software', 'solve', 'someday', 'stat', 'statistic', 'stats', 'study', 'submission', 'submit', 'ta', 'test', 'thing', 'tho', 'tmr', 'tomorrow', 'tonight', 'ugh', 'unknown', 'urgent', 'v1', 'v2', 'v3', 'v4', 'v5', 'week', 'weekly', 'whenever', 'work', 'working', 'write', 'writing']

In [20]:
from sklearn.preprocessing import StandardScaler

# Initialize StandardScaler
scaler = StandardScaler()

# Scale 'Deadline (days)' and 'Time Taken (hours)'
df[['Deadline (days)_scaled', 'Time Taken (hours)_scaled']] = scaler.fit_transform(df[['Deadline (days)', 'Time Taken (hours)']])

print("Scaled Numerical Features (first 5 rows):")
display(df[['Deadline (days)', 'Deadline (days)_scaled', 'Time Taken (hours)', 'Time Taken (hours)_scaled']].head())

Scaled Numerical Features (first 5 rows):

,Deadline (days),Deadline (days)_scaled,Time Taken (hours),Time Taken (hours)_scaled
0,7,1.483185,1.7,-0.921226
1,2,-0.939528,1.3,-1.152559
2,5,0.514100,2.4,-0.516393
3,5,0.514100,6.1,1.623437
4,1,-1.424071,3.9,0.351106

### Step 9: DATA SPLITTING

In [21]:
from sklearn.model_selection import train_test_split

# Assuming 'Category' is the target for classification and 'Time Taken (hours)' for regression
# For multi-task learning, we might have multiple targets.
# Here, we'll demonstrate splitting for a generic ML task, focusing on features.

X = final_features_df # Our combined feature set

# If you had a specific target variable (e.g., 'Category' or 'Time Taken (hours)'), you would define y as follows:
# y_category = df['Category_Encoded'] # For classification
# y_time_taken = df['Time Taken (hours)'] # For regression

# For now, we'll just split X to demonstrate the feature set split.
# In a real scenario, you'd split X and y together to maintain correspondence.

X_train, X_test, _, _ = train_test_split(X, X, test_size=0.2, random_state=42)

print(f"Shape of training features (X_train): {X_train.shape}")
print(f"Shape of testing features (X_test): {X_test.shape}")

print("\nSample of training features (first 5 rows):")
display(X_train.head())

Shape of training features (X_train): (800, 165)
Shape of testing features (X_test): (200, 165)

Sample of training features (first 5 rows):

,Category_Exam,Category_Homework,Category_Project,Category_Quiz,Importance_High,Importance_Low,Importance_Medium,Difficulty_Encoded,Task_Length,Urgency_Flag,...,v3,v4,v5,week,weekly,whenever,work,working,write,writing
29,1.0,0.0,0.0,0.0,0.0,0.0,1.0,1,4,0,...,0.0,0.0,0.0,0.450272,0.0,0.000000,0.0,0.0,0.0,0.000000
535,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0,4,0,...,0.0,0.0,0.0,0.000000,0.0,0.000000,0.0,0.0,0.0,0.000000
695,0.0,0.0,1.0,0.0,1.0,0.0,0.0,1,4,1,...,0.0,0.0,0.0,0.000000,0.0,0.000000,0.0,0.0,0.0,0.648632
557,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0,5,0,...,0.0,0.0,0.0,0.000000,0.0,0.000000,0.0,0.0,0.0,0.000000
836,0.0,0.0,0.0,1.0,0.0,1.0,0.0,1,4,0,...,0.0,0.0,0.0,0.000000,0.0,0.510736,0.0,0.0,0.0,0.000000

In [22]:
from sklearn.model_selection import train_test_split

# Assuming 'Category' is the target for classification and 'Time Taken (hours)' for regression
# For multi-task learning, we might have multiple targets.
# Here, we'll demonstrate splitting for a generic ML task, focusing on features.

X = final_features_df # Our combined feature set

# If you had a specific target variable (e.g., 'Category' or 'Time Taken (hours)'), you would define y as follows:
# y_category = df['Category_Encoded'] # For classification
# y_time_taken = df['Time Taken (hours)'] # For regression

# For now, we'll just split X to demonstrate the feature set split.
# In a real scenario, you'd split X and y together to maintain correspondence.

X_train, X_test, _, _ = train_test_split(X, X, test_size=0.2, random_state=42)

print(f"Shape of training features (X_train): {X_train.shape}")
print(f"Shape of testing features (X_test): {X_test.shape}")

print("\nSample of training features (first 5 rows):")
display(X_train.head())

Shape of training features (X_train): (800, 165)
Shape of testing features (X_test): (200, 165)

Sample of training features (first 5 rows):

,Category_Exam,Category_Homework,Category_Project,Category_Quiz,Importance_High,Importance_Low,Importance_Medium,Difficulty_Encoded,Task_Length,Urgency_Flag,...,v3,v4,v5,week,weekly,whenever,work,working,write,writing
29,1.0,0.0,0.0,0.0,0.0,0.0,1.0,1,4,0,...,0.0,0.0,0.0,0.450272,0.0,0.000000,0.0,0.0,0.0,0.000000
535,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0,4,0,...,0.0,0.0,0.0,0.000000,0.0,0.000000,0.0,0.0,0.0,0.000000
695,0.0,0.0,1.0,0.0,1.0,0.0,0.0,1,4,1,...,0.0,0.0,0.0,0.000000,0.0,0.000000,0.0,0.0,0.0,0.648632
557,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0,5,0,...,0.0,0.0,0.0,0.000000,0.0,0.000000,0.0,0.0,0.0,0.000000
836,0.0,0.0,0.0,1.0,0.0,1.0,0.0,1,4,0,...,0.0,0.0,0.0,0.000000,0.0,0.510736,0.0,0.0,0.0,0.000000

In [23]:
df

,Task Text,Category,Difficulty,Deadline (days),Time Taken (hours),Importance,Cleaned_Task_Text,Processed_Task_Text,Difficulty_Encoded,Task_Length,Urgency_Flag,Time_Pressure,Deadline (days)_scaled,Time Taken (hours)_scaled,Time Taken (hours)_clipped
0,those calculus problems from class no rush,Homework,Medium,7,1.7,Low,those calculus problems from class no rush,calculus problem class rush,1,4,0,4.117647,1.483185,-0.921226,1.7
1,prep for databases quiz,Quiz,Easy,2,1.3,High,prep for databases quiz,prep database quiz,0,3,0,1.538462,-0.939528,-1.152559,1.3
2,do CHEM hw,Homework,Medium,5,2.4,Medium,do chem homework,chem homework,1,2,0,2.083333,0.514100,-0.516393,2.4
3,lit midterm prep this week,Exam,Hard,5,6.1,Medium,lit midterm prep this week,lit midterm prep week,2,4,0,0.819672,0.514100,1.623437,6.1
4,oh no bioo exam tmr study literally tonight,Exam,Medium,1,3.9,High,oh no biologyo exam tmr study literally tonight,oh biologyo exam tmr study literally tonight,1,7,0,0.256410,-1.424071,0.351106,3.9
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,db assignment ch7 scheduled,Homework,Easy,5,1.8,Medium,db assignment ch7 scheduled,db assignment ch7 scheduled,0,4,0,2.777778,0.514100,-0.863392,1.8
996,mini test BIO - low priority,Quiz,Hard,7,1.5,Low,mini test biology low priority,mini test biology low priority,2,5,0,4.666667,1.483185,-1.036892,1.5
997,bio hw ch6 - this week,Homework,Hard,3,5.0,Medium,biology homework ch6 this week,biology homework ch6 week,2,4,0,0.600000,-0.454985,0.987271,5.0
998,networks final exam study idk when,Exam,Hard,6,5.0,Low,networks final exam study unknown when,network final exam study unknown,2,5,0,1.200000,0.998642,0.987271,5.0
999,network project draft v1 due tmr!!,Project,Hard,1,6.7,High,network project draft v1 due tmr,network project draft v1 due tmr,2,6,0,0.149254,-1.424071,1.970436,6.7

### Step 10: MODEL TRAINING
Train three classifiers for Category and Importance, and three regressors for Time Taken. We re-fit TF-IDF only on the training split — correct ML practice.

In [24]:
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import TfidfVectorizer

# ── Features and targets ──────────────────────────────────────────
# At prediction time we only have the task text, so X = text only.
X_raw        = df['Processed_Task_Text']
y_category   = df['Category']            # 4 classes: Exam, Homework, Project, Quiz
y_importance = df['Importance']          # 3 classes: Low, Medium, High
y_time       = df['Time Taken (hours)']  # regression target: 1.0 – 7.0 hrs

# ── 80/20 split (stratified on Category for balanced classes) ─────
X_tr_raw, X_te_raw, y_cat_tr, y_cat_te = train_test_split(
    X_raw, y_category, test_size=0.2, random_state=42, stratify=y_category
)
_, _, y_imp_tr,  y_imp_te  = train_test_split(X_raw, y_importance, test_size=0.2, random_state=42, stratify=y_category)
_, _, y_time_tr, y_time_te = train_test_split(X_raw, y_time,       test_size=0.2, random_state=42, stratify=y_category)

# ── Fit TF-IDF on training data ONLY ─────────────────────────────
tfidf = TfidfVectorizer(max_features=500)
X_tr = tfidf.fit_transform(X_tr_raw)
X_te = tfidf.transform(X_te_raw)

print(f"Train : {X_tr.shape[0]} samples")
print(f"Test  : {X_te.shape[0]} samples")
print(f"Features: {X_tr.shape[1]}")

Train : 800 samples
Test  : 200 samples
Features: 150

In [25]:
from sklearn.naive_bayes import MultinomialNB
from sklearn.ensemble import RandomForestClassifier
from sklearn.svm import LinearSVC
from sklearn.metrics import accuracy_score, classification_report

def train_classifiers(X_tr, X_te, y_tr, y_te, label):
    models = {
        'Naive Bayes'  : MultinomialNB(),
        'Random Forest': RandomForestClassifier(n_estimators=100, random_state=42, n_jobs=-1),
        'SVM'          : LinearSVC(random_state=42, max_iter=2000)
    }
    results = {}
    print(f"\n{'='*45}\n{label}\n{'='*45}")
    for name, model in models.items():
        model.fit(X_tr, y_tr)
        preds = model.predict(X_te)
        acc   = accuracy_score(y_te, preds)
        results[name] = {'model': model, 'accuracy': acc, 'preds': preds}
        print(f"  {name:20s} -> Accuracy: {acc:.4f}")
    best_name = max(results, key=lambda k: results[k]['accuracy'])
    best      = results[best_name]
    print(f"\n  Best: {best_name} ({best['accuracy']:.4f})")
    print(classification_report(y_te, best['preds']))
    return best['model'], best_name, best['accuracy']

best_cat_model, best_cat_name, cat_acc = train_classifiers(
    X_tr, X_te, y_cat_tr, y_cat_te, "CATEGORY CLASSIFICATION"
)
best_imp_model, best_imp_name, imp_acc = train_classifiers(
    X_tr, X_te, y_imp_tr, y_imp_te, "IMPORTANCE CLASSIFICATION"
)

=============================================
CATEGORY CLASSIFICATION
=============================================
  Naive Bayes          -> Accuracy: 0.9950
  Random Forest        -> Accuracy: 0.9950
  SVM                  -> Accuracy: 0.9950

  Best: Naive Bayes (0.9950)
              precision    recall  f1-score   support

        Exam       1.00      0.98      0.99        50
    Homework       1.00      1.00      1.00        50
     Project       1.00      1.00      1.00        50
        Quiz       0.98      1.00      0.99        50

    accuracy                           0.99       200
   macro avg       1.00      0.99      0.99       200
weighted avg       1.00      0.99      0.99       200


=============================================
IMPORTANCE CLASSIFICATION
=============================================
  Naive Bayes          -> Accuracy: 0.7850
  Random Forest        -> Accuracy: 0.8350
  SVM                  -> Accuracy: 0.8200

  Best: Random Forest (0.8350)
              precision    recall  f1-score   support

        High       0.96      0.84      0.89        55
         Low       0.81      0.74      0.77        62
      Medium       0.79      0.90      0.84        83

    accuracy                           0.83       200
   macro avg       0.85      0.83      0.84       200
weighted avg       0.84      0.83      0.84       200

In [26]:
from sklearn.linear_model import Ridge
from sklearn.ensemble import RandomForestRegressor
from sklearn.svm import LinearSVR
from sklearn.metrics import mean_absolute_error, r2_score

def train_regressors(X_tr, X_te, y_tr, y_te, label):
    models = {
        'Ridge Regression': Ridge(alpha=1.0),
        'Random Forest'   : RandomForestRegressor(n_estimators=100, random_state=42, n_jobs=-1),
        'LinearSVR'       : LinearSVR(random_state=42, max_iter=2000)
    }
    results = {}
    print(f"\n{'='*45}\n{label}\n{'='*45}")
    for name, model in models.items():
        model.fit(X_tr, y_tr)
        preds = model.predict(X_te)
        mae   = mean_absolute_error(y_te, preds)
        r2    = r2_score(y_te, preds)
        results[name] = {'model': model, 'mae': mae, 'r2': r2}
        print(f"  {name:20s} -> MAE: {mae:.4f} hrs | R2: {r2:.4f}")
    best_name = min(results, key=lambda k: results[k]['mae'])
    best = results[best_name]
    print(f"\n  Best: {best_name} (MAE={best['mae']:.4f} hrs, R2={best['r2']:.4f})")
    return best['model'], best_name, best['mae']

best_time_model, best_time_name, time_mae = train_regressors(
    X_tr, X_te, y_time_tr, y_time_te, "TIME ESTIMATION (hours)"
)

=============================================
TIME ESTIMATION (hours)
=============================================
  Ridge Regression     -> MAE: 1.0033 hrs | R2: 0.4780
  Random Forest        -> MAE: 0.9593 hrs | R2: 0.5013
  LinearSVR            -> MAE: 1.0040 hrs | R2: 0.4625

  Best: Random Forest (MAE=0.9593 hrs, R2=0.5013)

In [27]:
import pandas as pd

summary = pd.DataFrame({
    'Target'    : ['Category',              'Importance',            'Time Taken'],
    'Best Model': [best_cat_name,           best_imp_name,           best_time_name],
    'Result'    : [f'Acc={cat_acc:.4f}',   f'Acc={imp_acc:.4f}',   f'MAE={time_mae:.4f} hrs'],
})
print("\n=== TRAINING SUMMARY ===")
print(summary.to_string(index=False))

=== TRAINING SUMMARY ===
    Target    Best Model         Result
  Category   Naive Bayes     Acc=0.9950
Importance Random Forest     Acc=0.8350
Time Taken Random Forest MAE=0.9593 hrs

### Step 11: EXPORT MODELS
Save the trained models and the TF-IDF vectorizer to disk. The Flask backend will load these files to serve predictions without re-training.

In [28]:
import joblib, os

os.makedirs('models', exist_ok=True)

joblib.dump(best_cat_model,  'models/category_model.pkl')
joblib.dump(best_imp_model,  'models/importance_model.pkl')
joblib.dump(best_time_model, 'models/time_model.pkl')
joblib.dump(tfidf,           'models/tfidf_vectorizer.pkl')

print("Models saved to ./models/")
print("  category_model.pkl   — predicts: Exam / Homework / Project / Quiz")
print("  importance_model.pkl — predicts: Low / Medium / High")
print("  time_model.pkl       — predicts: estimated hours (float)")
print("  tfidf_vectorizer.pkl — transforms raw text to feature vector")
print("\nNext step: Flask backend will import these files.")

Models saved to ./models/
  category_model.pkl   — predicts: Exam / Homework / Project / Quiz
  importance_model.pkl — predicts: Low / Medium / High
  time_model.pkl       — predicts: estimated hours (float)
  tfidf_vectorizer.pkl — transforms raw text to feature vector

Next step: Flask backend will import these files.

### Step 12: IMPROVED MODEL TRAINING
Importance model now uses **TF-IDF + deadline** as features (deadline is the strongest real-world signal).
Time model now uses **TF-IDF + category** as features (category determines how long a task takes).

In [29]:
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.preprocessing import StandardScaler, LabelEncoder
from scipy.sparse import hstack, csr_matrix
import numpy as np

# ── Re-split with the new dataset ────────────────────────────────
X_raw        = df['Processed_Task_Text']
y_category   = df['Category']
y_importance = df['Importance']
y_time       = df['Time Taken (hours)']

X_tr_raw, X_te_raw, y_cat_tr, y_cat_te = train_test_split(
    X_raw, y_category, test_size=0.2, random_state=42, stratify=y_category
)
_, _, y_imp_tr,  y_imp_te  = train_test_split(X_raw, y_importance, test_size=0.2, random_state=42, stratify=y_category)
_, _, y_time_tr, y_time_te = train_test_split(X_raw, y_time,       test_size=0.2, random_state=42, stratify=y_category)

# ── TF-IDF fit on train only ──────────────────────────────────────
tfidf2 = TfidfVectorizer(max_features=500)
X_tr_tfidf = tfidf2.fit_transform(X_tr_raw)
X_te_tfidf = tfidf2.transform(X_te_raw)

# ── Deadline feature for importance model ─────────────────────────
deadline_scaler = StandardScaler()
dl_tr = df.loc[X_tr_raw.index, 'Deadline (days)'].values.reshape(-1, 1)
dl_te = df.loc[X_te_raw.index, 'Deadline (days)'].values.reshape(-1, 1)
dl_tr_scaled = deadline_scaler.fit_transform(dl_tr)
dl_te_scaled = deadline_scaler.transform(dl_te)

X_tr_imp = hstack([X_tr_tfidf, csr_matrix(dl_tr_scaled)])
X_te_imp = hstack([X_te_tfidf, csr_matrix(dl_te_scaled)])

# ── Category feature for time model ──────────────────────────────
le_cat = LabelEncoder()
cat_tr_enc = le_cat.fit_transform(df.loc[X_tr_raw.index, 'Category']).reshape(-1, 1)
cat_te_enc = le_cat.transform(df.loc[X_te_raw.index, 'Category']).reshape(-1, 1)

X_tr_time = hstack([X_tr_tfidf, csr_matrix(cat_tr_enc)])
X_te_time = hstack([X_te_tfidf, csr_matrix(cat_te_enc)])

print("Feature shapes:")
print(f"  Category model   : {X_tr_tfidf.shape}")
print(f"  Importance model : {X_tr_imp.shape}  (TF-IDF + deadline)")
print(f"  Time model       : {X_tr_time.shape} (TF-IDF + category)")

Feature shapes:
  Category model   : (800, 150)
  Importance model : (800, 151)  (TF-IDF + deadline)
  Time model       : (800, 151) (TF-IDF + category)

In [30]:
from sklearn.naive_bayes import MultinomialNB
from sklearn.ensemble import RandomForestClassifier, GradientBoostingClassifier
from sklearn.svm import LinearSVC
from sklearn.metrics import accuracy_score, classification_report

def train_classifiers_v2(X_tr, X_te, y_tr, y_te, label, allow_nb=True):
    models = {}
    if allow_nb:
        models['Naive Bayes']       = MultinomialNB()
    models['Random Forest']         = RandomForestClassifier(n_estimators=200, random_state=42, n_jobs=-1)
    models['SVM']                   = LinearSVC(random_state=42, max_iter=3000)
    models['Gradient Boosting']     = GradientBoostingClassifier(n_estimators=150, random_state=42)

    results = {}
    print(f"\n{'='*48}\n{label}\n{'='*48}")
    for name, model in models.items():
        Xtr = X_tr.toarray() if name == 'Gradient Boosting' else X_tr
        Xte = X_te.toarray() if name == 'Gradient Boosting' else X_te
        model.fit(Xtr, y_tr)
        preds = model.predict(Xte)
        acc   = accuracy_score(y_te, preds)
        results[name] = {'model': model, 'accuracy': acc, 'preds': preds}
        print(f"  {name:22s} -> Accuracy: {acc:.4f}")
    best_name = max(results, key=lambda k: results[k]['accuracy'])
    best      = results[best_name]
    print(f"\n  Best: {best_name} ({best['accuracy']:.4f})")
    print(classification_report(y_te, best['preds']))
    return best['model'], best_name, best['accuracy']

best_cat_model2, best_cat_name2, cat_acc2 = train_classifiers_v2(
    X_tr_tfidf, X_te_tfidf, y_cat_tr, y_cat_te,
    "CATEGORY  (TF-IDF only)", allow_nb=True
)
best_imp_model2, best_imp_name2, imp_acc2 = train_classifiers_v2(
    X_tr_imp, X_te_imp, y_imp_tr, y_imp_te,
    "IMPORTANCE (TF-IDF + deadline)", allow_nb=False
)

================================================
CATEGORY  (TF-IDF only)
================================================
  Naive Bayes            -> Accuracy: 0.9950
  Random Forest          -> Accuracy: 0.9950
  SVM                    -> Accuracy: 0.9950
  Gradient Boosting      -> Accuracy: 0.9900

  Best: Naive Bayes (0.9950)
              precision    recall  f1-score   support

        Exam       1.00      0.98      0.99        50
    Homework       1.00      1.00      1.00        50
     Project       1.00      1.00      1.00        50
        Quiz       0.98      1.00      0.99        50

    accuracy                           0.99       200
   macro avg       1.00      0.99      0.99       200
weighted avg       1.00      0.99      0.99       200


================================================
IMPORTANCE (TF-IDF + deadline)
================================================
  Random Forest          -> Accuracy: 1.0000
  SVM                    -> Accuracy: 0.9950
  Gradient Boosting      -> Accuracy: 1.0000

  Best: Random Forest (1.0000)
              precision    recall  f1-score   support

        High       1.00      1.00      1.00        55
         Low       1.00      1.00      1.00        62
      Medium       1.00      1.00      1.00        83

    accuracy                           1.00       200
   macro avg       1.00      1.00      1.00       200
weighted avg       1.00      1.00      1.00       200

In [31]:
from sklearn.linear_model import Ridge
from sklearn.ensemble import RandomForestRegressor, GradientBoostingRegressor
from sklearn.svm import LinearSVR
from sklearn.metrics import mean_absolute_error, r2_score

def train_regressors_v2(X_tr, X_te, y_tr, y_te, label):
    models = {
        'Ridge Regression' : Ridge(alpha=1.0),
        'Random Forest'    : RandomForestRegressor(n_estimators=200, random_state=42, n_jobs=-1),
        'LinearSVR'        : LinearSVR(random_state=42, max_iter=3000),
        'Gradient Boosting': GradientBoostingRegressor(n_estimators=150, random_state=42),
    }
    results = {}
    print(f"\n{'='*48}\n{label}\n{'='*48}")
    for name, model in models.items():
        Xtr = X_tr.toarray() if name == 'Gradient Boosting' else X_tr
        Xte = X_te.toarray() if name == 'Gradient Boosting' else X_te
        model.fit(Xtr, y_tr)
        preds = model.predict(Xte)
        mae   = mean_absolute_error(y_te, preds)
        r2    = r2_score(y_te, preds)
        results[name] = {'model': model, 'mae': mae, 'r2': r2}
        print(f"  {name:22s} -> MAE: {mae:.4f} hrs | R2: {r2:.4f}")
    best_name = min(results, key=lambda k: results[k]['mae'])
    best = results[best_name]
    print(f"\n  Best: {best_name} (MAE={best['mae']:.4f} hrs, R2={best['r2']:.4f})")
    return best['model'], best_name, best['mae']

best_time_model2, best_time_name2, time_mae2 = train_regressors_v2(
    X_tr_time, X_te_time, y_time_tr, y_time_te,
    "TIME ESTIMATION (TF-IDF + category)"
)

================================================
TIME ESTIMATION (TF-IDF + category)
================================================
  Ridge Regression       -> MAE: 0.9748 hrs | R2: 0.4977
  Random Forest          -> MAE: 0.9625 hrs | R2: 0.4983
  LinearSVR              -> MAE: 0.9663 hrs | R2: 0.4922
  Gradient Boosting      -> MAE: 0.9462 hrs | R2: 0.5047

  Best: Gradient Boosting (MAE=0.9462 hrs, R2=0.5047)

In [32]:
import pandas as pd

summary2 = pd.DataFrame({
    'Target'    : ['Category', 'Importance', 'Time Taken'],
    'Features'  : ['TF-IDF', 'TF-IDF + deadline', 'TF-IDF + category'],
    'Best Model': [best_cat_name2, best_imp_name2, best_time_name2],
    'Result'    : [
        f'Acc={cat_acc2:.4f}',
        f'Acc={imp_acc2:.4f}',
        f'MAE={time_mae2:.4f} hrs',
    ],
})
print("\n=== IMPROVED TRAINING SUMMARY ===")
print(summary2.to_string(index=False))

=== IMPROVED TRAINING SUMMARY ===
    Target          Features        Best Model         Result
  Category            TF-IDF       Naive Bayes     Acc=0.9950
Importance TF-IDF + deadline     Random Forest     Acc=1.0000
Time Taken TF-IDF + category Gradient Boosting MAE=0.9462 hrs

### Step 13: EXPORT IMPROVED MODELS
Saves all model files including the deadline scaler and category encoder needed for the prediction pipeline in Flask.

In [33]:
import joblib, os

os.makedirs('models', exist_ok=True)

joblib.dump(best_cat_model2,  'models/category_model.pkl')
joblib.dump(best_imp_model2,  'models/importance_model.pkl')
joblib.dump(best_time_model2, 'models/time_model.pkl')
joblib.dump(tfidf2,           'models/tfidf_vectorizer.pkl')
joblib.dump(deadline_scaler,  'models/deadline_scaler.pkl')
joblib.dump(le_cat,           'models/category_encoder.pkl')

print("All models exported to ./models/")
print("  category_model.pkl    — input: TF-IDF")
print("  importance_model.pkl  — input: TF-IDF + deadline")
print("  time_model.pkl        — input: TF-IDF + category")
print("  tfidf_vectorizer.pkl  — text transformer")
print("  deadline_scaler.pkl   — deadline normaliser")
print("  category_encoder.pkl  — category label encoder")

All models exported to ./models/
  category_model.pkl    — input: TF-IDF
  importance_model.pkl  — input: TF-IDF + deadline
  time_model.pkl        — input: TF-IDF + category
  tfidf_vectorizer.pkl  — text transformer
  deadline_scaler.pkl   — deadline normaliser
  category_encoder.pkl  — category label encoder